name: Validate Pull Request

# This workflow verifies that the site will build for pull requests.
on: [pull_request]

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: true

    # Setup Hugo so we're ready to run the build.
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: '0.61.0'
        extended: true

    # Run the build - this will fail if there are broken links etc.
    - name: Build
      run: make build
